AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CalculateLambdaKotlinRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CalculateLambdaKotlinRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -   Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Policies:
        -   PolicyName: CalculateLambdaKotlinRolePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -   Effect: Allow
                    Action:
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                    Resource: '*'

  CalculateLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: jp.ne.naokiur.handlers.calculate.App
      Runtime: java8
  DynamodbLambdaKotlinRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DynamodbLambdaKotlinRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -   Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Policies:
        -   PolicyName: DynamodbLambdaKotlinRolePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -   Effect: Allow
                    Action:
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                      - dynamodb:*Item
                      - dynamodb:Scan
                      - dynamodb:Query
                      - dynamodb:List*
                      - logs:PutLogEvents
                    Resource: '*'

  DynamodbLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: jp.ne.naokiur.handlers.dynamodb.App
      Runtime: java8
  S3LambdaKotlinRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: S3LambdaKotlinRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -   Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Policies:
        -   PolicyName: S3LambdaKotlinRolePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -   Effect: Allow
                    Action:
                      - logs:CreateLogStream
                      - logs:PutLogEvents
                      - s3:List*
                      - s3:Get*
                    Resource: '*'

  S3LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: jp.ne.naokiur.handlers.s3.App
      Runtime: java8