AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Globals:
  Function:
    Timeout: 3

Resources:
  CalculateLambdaPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: calculate.app.lambda_handler
      Runtime: python3.6
  DynamodbLambdaPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: dynamodb.app.lambda_handler
      Runtime: python3.6
  S3LambdaPythonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: s3.app.lambda_handler
      Runtime: python3.6